apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: testing
data:
  APP_ENV: "staging"
  APP_PORT: "3000"
  LOG_LEVEL: "debug"
  DB_HOST: "mysql-service"           # Kubernetes service name
  DB_PORT: "3306"
  DB_NAME: "krishinest"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
